name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Run specs
        run: bundle exec rspec

      - name: Build gem
        run: gem build mdx-tex.gemspec

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
